### ISSUE TITLE
Quiz timer

### ISSUE THREAD

**Issue by MarvinKweyu** [MarvinKweyu/AssessmentApplication#2]
Add a timer to the student quiz page as set in the teacher's account. Let the timer lockout further submission and redirect to the results page.

**Comment by jtryan** [comment]
I would be interested in helping. Do you have any more details on the request?.

**Comment by MarvinKweyu** [comment]
Hey @jtryan, doing a merge from one of the branches in a few regarding the teacher's side time. Added a `duration` field to the model. So on this, can we get it to say not pause upon logging out? This is to prevent the student pausing a test, doing some research and getting back to find the time the same.

**Comment by jtryan** [comment]
See my comments in #7. You need to clear the local storage if they leave the page. I clear it if the timer ends. You will also want to redirect on timer ending.  I think those are easy to add to  the code.

**Comment by MarvinKweyu** [comment]
Great John. It will act as the bolier plate for further improvements. It will work for the meeantime.

**Comment by MarvinKweyu** [comment]
Take a look at the review on `main.js`? #7
