### ISSUE TITLE
Writing forms tests (django)

### ISSUE THREAD

**Issue by durvalcarvalho** [MarvinKweyu/AssessmentApplication#3]
Create tests for the following forms: 

- [x] TeacherSignUpForm
- [x] StudentSignUpForm
- [x] BaseAnswerInlineFormSet

**Comment by durvalcarvalho** [comment]
I think it would be nice to create more tests

**Comment by MarvinKweyu** [comment]
Awesome @durvalcarvalho . Go right ahead.

**Comment by durvalcarvalho** [comment]
After the #6 Pull Request approve, this issue could be closed
